AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Function that serves infromation about cats from DynamoDB'
Resources:
  kociamadkaplFetchCats:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: pl.kociamadka.App::handleRequest
      Runtime: java11
      CodeUri: fetchCatsFunction
      Description: ''
      MemorySize: 512
      Timeout: 15
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /kociamadkaplFetchCats
            Method: GET
