AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  kociamadkaplFetchCats:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: pl.kociamadka.App::handleRequest
      Runtime: java11
      CodeUri: fetchCatsFunction
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: >-
        arn:aws:iam::634368661050:role/service-role/kociamadkaplFetchCats-role-xkb3o0em
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /kociamadkaplFetchCats
            Method: ANY